services:
  - type: web
    name: uamp-frontend
    env: static
    plan: free
    buildCommand: ng build --configuration production
    publishDirectory: dist/uamp-angular
    envVars:
      - key: API_BASE_URL
        value: https://uamp.vercel.app/api
      - key: WEBSOCKET_URL
        value: wss://uamp.vercel.app/ws
